apiVersion: v1
kind: DeploymentConfig
metadata:
  name: canary
spec:
  replicas: 1
  selector:
    run: canary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: canary
    spec:
      containers:
      - image: openshift/hello-openshift
        imagePullPolicy: Always
        name: hello
        env:
          - name: RESPONSE
            value: Hello from Canary
      restartPolicy: Always
  triggers:
  - type: ConfigChange
